### ISSUE TITLE
\LizardsAndPumpkins\Http\HttpUnknownMethodRequest::setMethodCode has protected access

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/catalog#1096]
\LizardsAndPumpkins\Http\HttpRequest::fromParameters
$unknownMethodRequest->setMethodCode($requestMethod);

Member has protected access -> if this line is hit, the code breaks

**Comment by tim-bezhashvyly** [comment]
I know this looks weird but, no it doesn't. And yes, this code is executed multiple times by tests. This is another oddity of PHP which can call a protected method of a derivative from the statically called parent class method.
