### ISSUE TITLE
File is not written if disk is full

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/catalog#946]
@nhp wrote on slack
> jetzt weiss ich warum das immer leer war: da meine platte voll war hat er nur von einem bruchteil der events auch das product-detail-json geschrieben.

So the product detail json is not written when disk is full. This should end in an exception

**Comment by tim-bezhashvyly** [comment]
How can this be safely implemented?

**Comment by Schrank** [comment]
File_put_contents returns bytes written, so we can check against the string length strlen()

**Comment by tim-bezhashvyly** [comment]
What about other key-value store implementations? Checking each snippet write is an overhead.

**Comment by Schrank** [comment]
The current problem is, that the disk is full. I expect from redis/varnish/... to take care of that themselves.

**Comment by tim-bezhashvyly** [comment]
Closed via:

- https://github.com/lizards-and-pumpkins/lib-search-engine-filesystem/issues/21
- https://github.com/lizards-and-pumpkins/lib-key-value-store-filesystem/issues/47
- https://github.com/lizards-and-pumpkins/lib-queue-backend-filesystem/issues/66
