### ISSUE TITLE
Update API docu

### ISSUE THREAD

**Issue by Schrank** [lizards-and-pumpkins/catalog#995]
https://github.com/lizards-and-pumpkins/catalog/wiki/API#update-content-block

Doesn't match implementation. We have a parameter `$keyGeneratorParameters = ['url_key' => $categorySlug];` which is merged into the body:

    $body = json_encode(array_merge(['content' => $content, 'context' => $context], $keyGeneratorParameters));

Missing:
- [ ] Current Version

**Comment by tim-bezhashvyly** [comment]
Duplicates #1037.
