### ISSUE TITLE
VM Usage Instructions are Incorrect

### ISSUE THREAD

**Issue by astorm** [lizards-and-pumpkins/catalog#996]
The following wiki page 

https://github.com/lizards-and-pumpkins/catalog/wiki/Demo-VM

contains incorrect usage information.

> Download or clone this repository
> Change to repository directory and run vagrant up

There is no repository directory in the `lizards-and-pumpkins/catalog` repository.  instructions should be updated to reflect current getting started steps for the VM.

**Comment by Schrank** [comment]
Thanks for telling us, fixed it.
